### ISSUE TITLE
Chrome: Can't connect to my account, always request to check verification email

### ISSUE THREAD

**Issue by shulard** [mitro-co/mitro#107]
Hello,

I've installed the mitro extension on Chrome Canary but  I can't get to my account.
I try to connect, then I received the verification email. I click on the link, it say that device is verified and I request me to connect again.

The 2 factor authentication process start, I enter the code but I see the given message :

![screenshot](https://cloud.githubusercontent.com/assets/482993/6209366/8a125f7a-b5c5-11e4-9d16-9a79a7d42dc9.png)

After that I do not receive any email, I think that extension is in sort of blocked mode...

**Comment by shulard** [comment]
I've the same in the standrd Chromme too...

**Comment by winstonhong** [comment]
Hello shulard.

The 2 factor authentication is NOT activated by dedault.

If you enable the 2 factor authentication process, you need to input the code generated by google authenticator.

Would you please shed me some light on how to enable two-factor authentication of Mitro if you have some ideas?

I am building another 2 factor authentication using OAuth2.0 standard.

http://oauth.net/2/

Thank you very much.

**Comment by shulard** [comment]
Hello,

I know that 2 factor authentication is not enabled by default. When I created my account, I have the possibility to enable it and it request me to install the Google Authenticator application.

Then I linked my account with that authenticator...

But with an active account, I don't know how to update this kind of preference...

**Comment by winstonhong** [comment]
Hello shulard.

When I check the source code, I find that the "logged in" webpage is set to "hide".

----------------------------------------------------------------------------

<div id="logged-in" class="hide" data-current-pane="secrets">

 <div class="link">
        <a id="two-factor-prefs" href="#">Two Factor Auth Preferences</a>
 </div>
----------------------------------------------------------------------------

"Two Factor Auth Preferences" is hidden by default.

My Chrome browser Version 40.0.2214.94

Quote your comment "When I created my account, I have the possibility to enable it and it request me to install the Google Authenticator application."

However, after I create a new Mitro account, I have NO possibility to enable two factor authentication.

My Logged-In user interface is shown as follows.

![mitrologgedin](https://cloud.githubusercontent.com/assets/2671418/6235326/b3e02ee6-b6af-11e4-8077-0472b0212efb.png)

Would you please show me a picture where to enable two factor authentication? Thank you very much.

If I can enable two factor authentication, I can continue to debug the issue.

I am developing new modules to create additional pop-up webpage for two factor authentication with OAuth2.0. This solution is quite different from google authenticator.

**Comment by roeler** [comment]
Does this extension interacts with the mitro.co backend or have you setup your own environment to connect with?

**Comment by winstonhong** [comment]
Hello roeler.

Thank you very much for your reply.

(1) This extension does NOT interact with the mitro.co backend.

(2) Instead, I setup our own environment to connect with the extension.

our config file for "external server"
browser-ext/login/common/config/config.release.js
*****************************************************************
var debugMode = false;
var MITRO_HOST = '192.168.108.147';
var MITRO_PORT = 8443;
var MITRO_AGENT_HOST = '192.168.108.147';
var MITRO_AGENT_PORT = 8443;
var FAILOVER_MITRO_HOST = null;
var FAILOVER_MITRO_PORT = null;
var FIREFOX;
var CHROME;
var SAFARI;
var WEBPAGE;
*****************************************************************

This extension is generated by "make release" (or "make firefox") instead of "make chrome-debug" (or "make firefox-debug").

https://192.168.108.147:8443/mitro-core/api/BuildMetadata
commit: 8c374fa
describe: fatal: No names found, cannot describe anything.
build time: 2015-02-16T20:18:34Z

(3) Even I use chrome and firefox download the extension from  
https://www.mitro.co/

My Chrome and Firefox browser still can NOT enable two-factor authentication (TFA) , no matter in SignUp or SignIn webpage.

(4) I can not fix out how to enable two-factor authentication (TFA) , no matter the extension built by myself or downloaded from mitro,co website

Would you please shed me some light on how to enable two-factor authentication (TFA) ? Thank you very much.

The source code of two-factor authentication (TFA)  is shown in the following link.

https://github.com/mitro-co/mitro/tree/master/mitro-core/java/server/src/co/mitro/twofactor
https://github.com/mitro-co/mitro/tree/master/mitro-core/java/server/src/co/mitro/twofactor

**Comment by vijayp** [comment]
Stephane, you can edit tfa prefs by clicking on the mitro button in the
browser, then the gear the "two factor auth preferences".

Winston, in order to update tfa preferences, your extension must provide a
signed token with nonce to the server which will validate this and then
generate a 2fa prefs page.  If you have not implemented that correctly,
then it will not work.
Vijay

**Comment by winstonhong** [comment]
Hello vijayp.

Thank you very much for your guidance.

After I enable 2FA in the 1st device Windows7/Firefox, I fail to login the two new devices Ubuntu14.04/Firefox or Ubuntu14.04/Chrome installed in other physical machine.

Then I disable 2FA in the 1st device Windows7/Firefox, I can login both new devices Ubuntu14.04/Firefox and Ubuntu14.04/Chrome installed in other physical machine.

Hello shulard.

I confirm your issue.  

I solve your issue by disabling 2FA in the 1st device Windows7/Firefox.

After I disable 2FA, I can login any new device successfully.

**Comment by shulard** [comment]
Hello,

Thanks for your answers, I confirm that disabling 2FA, solve my issue !

Thanks
